import fs from 'node:fs';
import path from 'node:path';
import { config } from '../config.js';
import { SpicetifyError } from './errors.js';

const ALLOWED_IMAGE_TYPES = ['image/jpeg', 'image/png', 'image/webp'];
const MAX_DATA_URI_BYTES = 900 * 1024; // base64 image budget; keeps final user.css well under maxCssBytes

// Only properties confirmed present via css-map.json / SpicetifyDefault color.ini.
// Do not add names here without verifying against the real installation first.
const KNOWN_COLOR_KEYS = [
  'text',
  'subtext',
  'main',
  'sidebar',
  'player',
  'card',
  'shadow',
  'selected-row',
  'button',
  'button-active',
  'button-disabled',
  'tab-active',
  'notification',
  'notification-error',
  'misc'
];

function themeDir() {
  return path.join(config.spicetify.themesDir, config.spicetify.themeName);
}

function validateDataUri(dataUri) {
  const match = /^data:(image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=]+)$/.exec(dataUri);
  if (!match) {
    throw new SpicetifyError('invalid_image', 'Formato de imagem inválido. Use JPEG, PNG ou WebP.');
  }
  const [, mime, base64] = match;
  if (!ALLOWED_IMAGE_TYPES.includes(mime)) {
    throw new SpicetifyError('unsupported_image_type', `Tipo de imagem não suportado: ${mime}`);
  }
  const byteLength = Math.ceil((base64.length * 3) / 4);
  if (byteLength > MAX_DATA_URI_BYTES) {
    throw new SpicetifyError(
      'image_too_large',
      `Imagem muito grande (${Math.round(byteLength / 1024)}KB). Reduza para até ${Math.round(MAX_DATA_URI_BYTES / 1024)}KB antes de aplicar.`,
      { byteLength, maxBytes: MAX_DATA_URI_BYTES }
    );
  }
  return { mime, base64, byteLength };
}

function buildColorIni(colors) {
  const lines = [`[${config.spicetify.themeName}]`];
  for (const key of KNOWN_COLOR_KEYS) {
    const value = colors?.[key];
    if (value) {
      if (!/^[0-9a-fA-F]{6}$/.test(value)) {
        throw new SpicetifyError('invalid_color', `Cor inválida para "${key}": ${value}`);
      }
      lines.push(`${key} = ${value}`);
    }
  }
  return lines.join('\n') + '\n';
}

function clamp01(value, fallback) {
  const n = Number(value);
  if (Number.isNaN(n)) return fallback;
  return Math.min(1, Math.max(0, n));
}

function buildUserCss({ backgroundDataUri, overlayOpacity, blurPx }) {
  const opacity = clamp01(overlayOpacity, 0.6);
  const blur = Math.min(20, Math.max(0, Number(blurPx) || 0));

  let css = '/* Generated by Spotify Organizer Theme Manager. Do not edit by hand. */\n';

  if (backgroundDataUri) {
    // .main-appShell-mainContent (from css-map.json) does not match any live DOM node on this
    // Spotify build — confirmed via real CDP inspection. .Root__main-view is the real opaque
    // layer (background-color: rgb(18,18,18)) covering the content area; .main-view-container
    // is the real transparent child confirmed to actually receive the background visually.
    css += `.Root__main-view {
  background-color: transparent !important;
}
.main-view-container {
  background-image: linear-gradient(rgba(13,13,15,${opacity}), rgba(13,13,15,${Math.min(1, opacity + 0.25)})), url("${backgroundDataUri}");
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;
}
`;
    if (blur > 0) {
      // EXPERIMENTAL: backdrop-filter never verified against real Spotify Desktop yet.
      // Do not surface as a stable feature until tested and visually confirmed.
      css += `.main-view-container {
  backdrop-filter: blur(${blur}px);
}
`;
    }

    // .main-yourLibraryX-libraryContainer confirmed via real CDP inspection: it's the actual
    // "Your Library" panel background (semantic, non-hashed class, stable across navigation),
    // and today it only receives a flat color from the `main` variable. Applying the same
    // background image here too, instead of leaving it a separate untouched area.
    css += `.main-yourLibraryX-libraryContainer {
  background-image: linear-gradient(rgba(13,13,15,${opacity}), rgba(13,13,15,${Math.min(1, opacity + 0.25)})), url("${backgroundDataUri}");
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;
}
`;

    // #Desktop_PanelContainer_Id (the right-hand Now Playing / Queue / Lyrics panel) already
    // receives our background-image correctly per computed style, but its own ::before
    // pseudo-element — an absolutely positioned, full-size, opaque layer painted from the same
    // `main` variable — sits on top of it and hides it completely. Confirmed via real CDP
    // inspection (DOM tree walk + temporary transparent override) that neutralizing only that
    // pseudo-element's background reveals the image without affecting album art, queue, or
    // lyrics content, which render in later layers above both.
    css += `#Desktop_PanelContainer_Id::before {
  background-color: transparent !important;
}
#Desktop_PanelContainer_Id {
  background-image: linear-gradient(rgba(13,13,15,${opacity}), rgba(13,13,15,${Math.min(1, opacity + 0.25)})), url("${backgroundDataUri}");
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;
}
`;
  }

  return css;
}

export function generateTheme({ colors, backgroundDataUri, overlayOpacity, blurPx }) {
  const dir = themeDir();
  fs.mkdirSync(dir, { recursive: true });

  if (backgroundDataUri) {
    validateDataUri(backgroundDataUri);
  }

  const colorIni = buildColorIni(colors || {});
  const userCss = buildUserCss({ backgroundDataUri, overlayOpacity, blurPx });

  const cssBytes = Buffer.byteLength(userCss, 'utf8');
  if (cssBytes > config.spicetify.maxCssBytes) {
    throw new SpicetifyError(
      'css_too_large',
      `user.css gerado (${Math.round(cssBytes / 1024)}KB) excede o limite de ${Math.round(config.spicetify.maxCssBytes / 1024)}KB.`
    );
  }

  fs.writeFileSync(path.join(dir, 'color.ini'), colorIni, 'utf8');
  fs.writeFileSync(path.join(dir, 'user.css'), userCss, 'utf8');

  return {
    themeDir: dir,
    colorIniBytes: Buffer.byteLength(colorIni, 'utf8'),
    userCssBytes: cssBytes
  };
}

export function readCurrentThemeConfig() {
  if (!fs.existsSync(config.spicetifyThemeConfigFile)) return null;
  try {
    return JSON.parse(fs.readFileSync(config.spicetifyThemeConfigFile, 'utf8'));
  } catch {
    return null;
  }
}

export function saveCurrentThemeConfig(themeConfig) {
  fs.mkdirSync(config.dataDir, { recursive: true });
  fs.writeFileSync(config.spicetifyThemeConfigFile, JSON.stringify(themeConfig, null, 2), 'utf8');
}
